### ISSUE TITLE
open http://localhost:8081/ doesn't work following recent server changes

### ISSUE THREAD

**Issue by golanlevin** [yonmaor1/p5-flipdots#4]
In situations where the display is offline, the system now has a nice error report when the server is launched. However, the webpage no longer launches in such a case. Specifically, when the device is not connected, 

```
$ node golive.js
$  open http://localhost:8081/
```
No longer opens the webpage. Instead, the browser reports an error:

```
This site can’t be reached
localhost refused to connect.
```

**Comment by yonmaor1** [comment]
resolved in PR #6
